### ISSUE TITLE
Subclasses SOMap and SSMap unnecessary, please remove

### ISSUE THREAD

**Issue by Coderrine** [rohitppathak/-softdev-2020-ai-part2#2]
The subclasses are unnecessary for scalability. The main interface supports Objects and therefore supports all subclasses of objects by default

**Comment by rohitppathak** [comment]
While all classes are subclasses of Objects, it doesn't make sense for a user to make a String->String map and then be allowed to put in an Object->String key-value pair. It does require more code to subclass, but there are only two methods to override, and their implementation mainly requires checking whether the types are consistent and then calling the super class's method. Making sure that the types line up seems to be the job of the map class, not the user (as we are in a statically-typed language).

**Comment by Coderrine** [comment]
Why doesn't it make sense? This is how Maps work in other languages, one example that comes to mind is Dictionaries in Python.

**Comment by rohitppathak** [comment]
That's true, but Python is a dynamically-typed language while CwC is statically-typed (so a user needs to specify what type of Map to create). It wouldn't make sense to for us to create a dynamically-typed map in a statically-typed language.

**Comment by Coderrine** [comment]
The type of the Object (whether key or value) is irrelevant to the functionality of the map, that's why we consider it unnecessary and duplicate code.

**Comment by kyleacmooney** [comment]
Sorry I really don't see the relevance of your comment about statically-typed languages vs. dynamically-types languages.  The map shouldn't be "dynamically-typed" in our recommendation.  What does that phrase mean?

**Comment by Coderrine** [comment]
To further clarify, we are focusing on the issue with scalability here. For example, right now we are just supporting Strings and Objects. As per your explanation and the requirements of the assignment, that means we actually need 4 subclasses: S -> S, S -> O, O -> S, O -> O. As the assignment asks for scalability explicitly, we see this as unnecessary code duplication as Map functionality is independent of the data type of the key/value since it will only ever use methods all Objects have.

**Comment by rohitppathak** [comment]
Basically that an SSMap should throw an error if we try to insert an key-value pair of Integer-String for instance. If we cannot do something like `String str = 1`, we feel like we should have type-checking in the Map.

**Comment by raacharya** [comment]
We understand your concern about scalability, but we don't see a better solution that also allows type checking

**Comment by kyleacmooney** [comment]
Can you please explain how the necessity of type-checking keys/values for a map implementation follows from "String str = 1" being invalid c code?  All object types should be supported as per the assignment text hence no type checking should be necessary.

**Comment by raacharya** [comment]
We used that example because in languages like Python, there aren't any types. That is why dictionaries don't do any type checking. In languages like Java, there is type-checking, so the map in Java checks the types of keys and values

**Comment by csstransky** [comment]
It's definitely possible to only have a map from Object to Object because of Strings inheriting from Objects, and it may even be easier to develop with, but after looking at the spec:
> Lastly, your Map should support mapping Strings to Strings and generally Object to Object. The performance of the Map class should be tuned to avoid pathological cases by rehashing when the load gets too high. Aim for fast code, whatever that means.

I imagine they want an explicit map that goes from String to String somewhere in the API for full credit. I guess you could argue getting rid of the String to Object map, but I personally want a SSMap and OOMap in the spec just to make the TAs happy.

**Comment by kyleacmooney** [comment]
I disagree.  "Support" in that sentence is at worst ambiguous, but it definitely doesn't imply we *need* an explicit separate Map *exclusively* for the purpose of String to String mappings given their emphasis on scalability.  

We would end up with n*n sub-classes of Map (where n is the number of sub-classes of Object) if we made new Maps for every combination in order to imitate Java generics.

**Comment by rohitppathak** [comment]
@Coderrine @kyleacmooney So it seems like we have different ideas on design. Rather than go back and forth on here at varying times, let's set a time and place to meet up and talk about this in person so we can reach a conclusion quicker. Let me know what your schedules look like; it should just be a quick meeting that we can do at WVH.

**Comment by csstransky** [comment]
Here are some Piazza questions that might help:
[https://piazza.com/class/k51bluky59n2jr?cid=331](https://piazza.com/class/k51bluky59n2jr?cid=331)
[https://piazza.com/class/k51bluky59n2jr?cid=341](https://piazza.com/class/k51bluky59n2jr?cid=341)

For this API, the answer on how it'll be implemented comes down to this:

> This boils down to the question whether I am allowed to write this:
> 
> `String  result  =  my_string_queue.pop();`
> 
> If you want to support this you will be pushed in one direction, if you don't you may have other choices.

I would argue that it's much nicer _to have the option_ to grab strings from a Map if we desire, instead of having to cast Objects, though you can then argue the problem of scope creep. For my purposes, I want a way to test Strings, and I would prefer to avoid having to cast things, _in my opinion_.

Jan gives this response on dealing with CwC and its absence of generics:

> Again play this out. You seem stuck on partial designs. 
> 
>  
> 
> Imagine an array of int and that we want to read and write to it.  What is the better design?
> 
>  
> 
> ```
> ia.push_back( 42 );
> int r = ia.get( 0 );
> ```
> 
>  
> 
> or 
> 
>  
> 
> ```
> ia.push_back( (void*) 42 );
> int r = (int) ia.get( 0 );
> ```
> 
>  
> 
> Functionally they are the same but in terms of correctness and ease of use they are miles apart.
> 
>  
> 
> As a side note: the idea of using void* to store any value is not portable.  The size of a void* is architecture dependent. There are still embedded boards where a void* is 16 bits. Not enough to store an int.

...

> Both of these solution would be correct as per A2 specification and you would not loose points. 
> 
>  
> 
> But, yes, I do believe that from an API it is clearly better to avoid the cast (because it is unchecked and you could get it wrong).
> 
>  
> 
> Now, you are right that I am only showing to lines of client code, what if the implementation of one was much simpler than the other.  That is a tradeoff and may well be a reason to pick one over the other.
> 
>  
> 
> Without proper support for generics there is no perfect answer.

Either direction is fine to the professors.

**Comment by kyleacmooney** [comment]
Interesting posts.  Hmmm... a user would still have to cast under the current map.h in this repo.  I can imagine a way to do that though: if we gave SSMap and friends their own get()/remove()/put() implementations alternative signatures with return types that correspond to what that specific sub-Map should return.  But we would have to copy-paste all of the code for remove(), put(), and get().

I'm okay with doing all of that just for an S-S Map for this assignment (again, from the above, I think we would still need to add some of that to the API), but am not sure that any other iteration like S-O O-S make any sense.  My partner isn't here right now though so if you are all okay with that, we can confirm that when she replies tomorrow I guess (I don't want to make the decision for both of us)?

**Comment by Coderrine** [comment]
Happy to discuss in person! I'm good to meet tomorrow at WVH, does 1:45 work for everyone?

**Comment by rohitppathak** [comment]
Unfortunately my partner and I have class from 1:35 - 5:05 tomorrow, is there any other time that works?

**Comment by Coderrine** [comment]
How about at 5:15?

**Comment by raacharya** [comment]
sounds good

**Comment by kaylindevchand** [comment]
Are you guys still in WVH?

**Comment by kyleacmooney** [comment]
Hey @kaylindevchand , sorry we actually did meet up and discussed.   Did you want to discuss anything specific?  Me and @Coderrine are still here at the lower table next to do the doors but we are leaving in a few minutes if you are still here.

**Comment by rohitppathak** [comment]
Just so everyone's on the same page, @raacharya, @Coderrine, @kyleacmooney and I talked about our design today. We wanted to minimize code duplication but wanted to create an invariant to restrict an SOMap from storing anything other than an String as its key and an SSMap from storing anything other than Strings as its key and value. This is why the `put` method is overriden in the two subclasses; these are meant to throw an error if the parameter passed in is not of the correct type. The `get` method is not overriden; the user of an SSMap, for instance, would need to cast the value back to a String. However, this should never fail due to the `put` invariant. This is also on the README so it should be visible when this issue gets closed.

**Comment by kaylindevchand** [comment]
Sounds good. Thanks for the update.
